package try

func Try[V any](V, error) (_ V) { return }
